version: "3.9"

services:
  ehali-db:
    image: postgres:15
    container_name: ehali-db
    environment:
      POSTGRES_DB: ehali
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ehali-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ehali"]
      interval: 5s
      timeout: 5s
      retries: 10

  ehali-backend-app:
    build: .
    container_name: ehali-backend-app
    depends_on:
      ehali-db:
        condition: service_healthy
    ports:
      - "8180:8383"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ehali-db:5432/ehali
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8383
    restart: unless-stopped

volumes:
  ehali-db-data: